services:
    web:
        container_name: asoud_api
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        # command: daphne config.asgi:application --bind 0.0.0.0 --port 8000
        environment:
            - DJANGO_SETTINGS_MODULE=config.settings.development
        volumes:
            # - ./:/asoud/
            - static_volume:/asoud/static
            - media_volume:/asoud/media
        ports:
            - 8000:8000
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
        develop:
            watch:
                - action: sync
                  path: .
                  target: /asoud/

    db:
        container_name: asoud_db
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

        volumes:
            - db_data:/var/lib/postgresql/data:rw

    redis:
        container_name: asoud_redis
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        command:
            [
                'redis-server',
                '--requirepass',
                'password123',
            ]
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    nginx:
        container_name: asoud_nginx
        image: nginx:1.25.3-alpine
        ports:
            - 80:80
        volumes:
            - ./data/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
            - static_volume:/asoud/static
            - media_volume:/asoud/media

volumes:
    db_data:
    redis_data:
    static_volume:
    media_volume:
